app/modules/community/models.py
from app import db

user_community = db.Table(
    "user_community",
    db.Column("user_id", db.Integer, db.ForeignKey("user.id"), primary_key=True),
    db.Column(
        "community_id", db.Integer, db.ForeignKey("community.id"), primary_key=True
    ),
)


class Community(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), nullable=False)
    description = db.Column(db.String(1000), nullable=False)
    owner_id = db.Column(db.Integer, db.ForeignKey("user.id"), nullable=False)

    owner = db.relationship("User", backref="owned_communities", lazy=True)
    members = db.relationship(
        "User",
        secondary=user_community,
        backref=db.backref("joined_communities", lazy="dynamic"),
        cascade="all",
    )

    shared_datasets = db.relationship("DataSet", backref="shared_community", lazy=True)

    def __repr__(self):
        return f"Community<{self.id}>"

app/modules/community/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class CommunityForm(FlaskForm):

    name = StringField("Name", validators=[DataRequired(), Length(max=256)])
    description = TextAreaField("Description", validators=[DataRequired()])
    submit = SubmitField("Save community")

app/modules/community/__init__.py
from core.blueprints.base_blueprint import BaseBlueprint

community_bp = BaseBlueprint("community", __name__, template_folder="templates")

app/modules/community/routes.py
from flask import flash, jsonify, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from app.modules.community import community_bp
from app.modules.community.forms import CommunityForm
from app.modules.community.models import Community
from app.modules.community.services import CommunityService
from app import db

community_service = CommunityService()


@community_bp.route("/community", methods=["GET"])
def index():
    all_communities = community_service.get_all()

    if current_user.is_authenticated:
        # Clasificar las comunidades si el usuario está autenticado
        owner_communities = [
            c for c in all_communities if c.owner_id == current_user.id
        ]
        member_communities = [
            c
            for c in all_communities
            if c.owner_id != current_user.id and current_user in c.members
        ]
        other_communities = [
            c
            for c in all_communities
            if c.owner_id != current_user.id and current_user not in c.members
        ]

        # Combinar las listas para enviarlas al template en el orden deseado
        sorted_communities = owner_communities + member_communities + other_communities
    else:
        # Si el usuario no está autenticado, mostrar todas las comunidades como "otras"
        sorted_communities = all_communities

    return render_template("community/index.html", communities=sorted_communities)


"""
CREATE
"""


@community_bp.route("/community/create", methods=["GET", "POST"])
@login_required
def create_community():
    form = CommunityForm()
    if form.validate_on_submit():
        result = community_service.create(
            name=form.name.data,
            description=form.description.data,
            owner_id=current_user.id,
        )
        return community_service.handle_service_response(
            result=result,
            errors=form.errors,
            success_url_redirect="community.index",
            success_msg="Community created successfully!",
            error_template="community/create.html",
            form=form,
        )
    return render_template("community/create.html", form=form)


"""
DELETE
"""


@community_bp.route("/community/delete/<int:community_id>", methods=["POST"])
@login_required
def delete_community(community_id):
    community = community_service.get_or_404(community_id)

    # Verificar que el usuario sea el propietario
    if community.owner_id != current_user.id:
        flash("You are not allowed to delete this community.", "danger")
        return redirect(url_for("community.index"))

    # Eliminar manualmente las relaciones de miembros
    community.members.clear()
    db.session.commit()

    # Eliminar la comunidad
    db.session.delete(community)
    db.session.commit()
    flash("Community deleted successfully.", "success")
    return redirect(url_for("community.index"))


"""
EDIT
"""


@community_bp.route("/community/edit/<int:community_id>", methods=["GET", "POST"])
@login_required
def edit_community(community_id):
    community = community_service.get_or_404(community_id)
    if community.owner_id != current_user.id:
        flash("You are not authorized to edit this community", "error")
        return redirect(url_for("community.index"))

    form = CommunityForm(obj=community)
    if form.validate_on_submit():
        result = community_service.update(
            community_id, name=form.name.data, description=form.description.data
        )
        return community_service.handle_service_response(
            result=result,
            errors=form.errors,
            success_url_redirect="community.index",
            success_msg="Community updated successfully!",
            error_template="community/edit.html",
            form=form,
        )
    return render_template("community/edit.html", form=form, community=community)


"""
READ BY ID
"""


@community_bp.route("/community/<int:community_id>", methods=["GET"])
def get_community(community_id):
    community = community_service.get_or_404(community_id)
    datasets = community.shared_datasets

    return render_template(
        "community/show.html", community=community, datasets=datasets
    )


@community_bp.route("/community/join", methods=["POST"])
@login_required
def join_community():
    community_id = request.json.get("community_id")

    if not community_id:
        return jsonify({"error": "Community ID is required"}), 400

    community = Community.query.get(community_id)

    if not community:
        return jsonify({"error": "Community not found"}), 404

    if community.owner_id == current_user.id:
        return jsonify({"error": "You are the owner of this community"}), 403

    if current_user in community.members:
        return jsonify({"error": "You are already a member of this community"}), 403

    community.members.append(current_user)
    db.session.commit()

    return jsonify({"message": "You have successfully joined the community"})


@community_bp.route("/community/leave", methods=["POST"])
@login_required
def leave_community():
    community_id = request.json.get("community_id")
    community = community_service.get_or_404(community_id)

    if not community:
        return jsonify({"error": "Community not found"}), 404

    if current_user not in community.members:
        return jsonify({"error": "You are not a member of this community"}), 400

    community.members.remove(current_user)
    db.session.commit()

    return jsonify({"message": "You have successfully left the community"})

app/modules/community/templates/community/create.html
{% extends "base_template.html" %}

{% block title %}Create community{% endblock %}

{% block content %}

<form method="POST" action="{{ url_for('community.create_community') }}">
    {{ form.hidden_tag() }}
    <div>
        {{ form.name.label }}<br>
        {{ form.name(size=32) }}
    </div>
    <div>
        {{ form.description.label }}<br>
        {{ form.description(rows=5) }}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>


{% endblock %}

{% block scripts %}
    <script src="{{ url_for('community.scripts') }}"></script>
{% endblock %}

app/modules/community/templates/community/edit.html
{% extends "base_template.html" %}

{% block title %}View community{% endblock %}

{% block content %}

<form method="POST" action="{{ url_for('community.edit_community', community_id=community.id) }}">
    {{ form.hidden_tag() }}
    <div>
        {{ form.name.label }}<br>
        {{ form.name(size=32) }}
    </div>
    <div>
        {{ form.description.label }}<br>
        {{ form.description(rows=5) }}
    </div>
    <div>
        {{ form.submit() }}
    </div>
</form>

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('community.scripts') }}"></script>
{% endblock %}

app/modules/community/templates/community/index.html
{% extends "base_template.html" %}

{% block title %}View community{% endblock %}

{% block content %}
<div>
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('community.create_community') }}" class="btn btn-primary mb-4">Create Community</a> <!-- Añadido mb-4 -->
    {% endif %}
</div>

{% if communities %}
    <div class="row">
        {% for community in communities %}
        <div class="col-12 col-md-4 mb-4"> <!-- Usamos col-12 para que ocupe todo en móviles -->
            <a href="{{ url_for('community.get_community', community_id=community.id) }}" class="text-decoration-none">
                <div class="card h-100 shadow-sm border-light">
                    <div class="card-body">
                        <h5 class="card-title">{{ community.name }}</h5>
                        <p class="card-text">{{ community.description }}</p>
                    </div>
                    {% if current_user.is_authenticated and community.owner_id == current_user.id %}
                    <div class="card-footer text-end">
                        <form action="{{ url_for('community.delete_community', community_id=community.id) }}" method="POST" style="display:inline;">
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                        </form>
                        <form action="{{ url_for('community.edit_community', community_id=community.id) }}" method="POST" style="display:inline;">
                            <button type="submit" class="btn btn-warning btn-sm">Edit</button>
                        </form>
                    </div>
                    {% endif %}
                    {% if community.owner_id != current_user.id and current_user.is_authenticated%}
                        {% if current_user in community.members %}
                            <!-- Botón para dejar de seguir la comunidad -->
                            <div class="card-footer text-end">
                                <button class="btn btn-danger btn-sm" 
                                        onclick="leaveCommunity('{{ community.id }}')">Leave Community</button>
                            </div>
                        {% else %}
                            <!-- Botón para unirse a la comunidad -->
                            <div class="card-footer text-end">
                                <button class="btn btn-primary btn-sm" 
                                        onclick="joinCommunity('{{ community.id }}')">Join Community</button>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
{% else %}
<p class="text-center" style="font-size: 1.5em;">
    You have no communities.
</p>
{% endif %}

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('community.scripts') }}"></script>

    <script>
        function joinCommunity(communityId) {
            fetch('/community/join', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ community_id: communityId })
            })
            .then(response => response.json())
            .then(data => {
                if (data.error) {
                    alert('Error: ' + data.error);
                } else {
                    alert('You have successfully joined the community!');
                    location.reload(); 
                }
            })
            .catch(error => console.error('Error:', error));
        }

        function leaveCommunity(communityId) {
    if (confirm("Are you sure you want to leave this community?")) {
        fetch('/community/leave', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({ community_id: communityId })
        })
        .then(response => response.json())
        .then(data => {
            if (data.error) {
                alert('Error: ' + data.error);
            } else {
                alert('You have successfully left the community!');
                location.reload(); 
            }
        })
        .catch(error => console.error('Error:', error));
    }
}

    </script>
{% endblock %}

app/modules/community/templates/community/show.html
{% extends "base_template.html" %}

{% block title %}Community details{% endblock %}

{% block content %}

<h1>{{ community.name }}</h1>
<p>{{ community.description }}</p>
<a href="{{ url_for('community.index') }}">Back to Communities</a>
{% for dataset in datasets %}
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex align-items-center justify-content-between">
                            <h2>

                                <a href="{{ dataset.get_uvlhub_doi() }}">
                                    {{ dataset.ds_meta_data.title }}
                                </a>

                            </h2>
                            <div>
                                <span class="badge bg-secondary">{{ dataset.get_cleaned_publication_type() }}</span>
                            </div>
                        </div>
                        <p class="text-secondary">{{ dataset.created_at.strftime('%B %d, %Y at %I:%M %p') }}</p>

                        <div class="row mb-2">

                            <div class="col-12">
                                <p class="card-text">{{ dataset.ds_meta_data.description }}</p>
                            </div>

                        </div>

                        <div class="row mb-2 mt-4">

                            <div class="col-12">
                                {% for author in dataset.ds_meta_data.authors %}
                                    <p class="p-0 m-0">
                                        {{ author.name }}
                                        {% if author.affiliation %}
                                            ({{ author.affiliation }})
                                        {% endif %}
                                        {% if author.orcid %}
                                            ({{ author.orcid }})
                                        {% endif %}
                                    </p>
                                {% endfor %}
                            </div>


                        </div>

                        <div class="row mb-2">

                            <div class="col-12">
                                <a href="{{ dataset.get_uvlhub_doi() }}">{{ dataset.get_uvlhub_doi() }}</a>
                                 <div id="dataset_doi_uvlhub_{{ dataset.id }}" style="display: none">
                                {{ dataset.get_uvlhub_doi() }}
                            </div>

                            <i data-feather="clipboard" class="center-button-icon"
                               style="cursor: pointer"
                               onclick="copyText('dataset_doi_uvlhub_{{ dataset.id }}')"></i>
                            </div>



                        </div>

                        <div class="row mb-2">

                            <div class="col-12">
                                {% for tag in dataset.ds_meta_data.tags.split(',') %}
                                    <span class="badge bg-secondary">{{ tag.strip() }}</span>
                                {% endfor %}
                            </div>

                        </div>

                        <div class="row  mt-4">
                            <div class="col-12">
                                <a href="{{ dataset.get_uvlhub_doi() }}" class="btn btn-outline-primary btn-sm"
                                   style="border-radius: 5px;">
                                    <i data-feather="eye" class="center-button-icon"></i>
                                    View dataset
                                </a>

                                <a href="/dataset/download/{{ dataset.id }}" class="btn btn-outline-primary btn-sm"
                                   style="border-radius: 5px;">
                                    <i data-feather="download" class="center-button-icon"></i>
                                    Download ({{ dataset.get_file_total_size_for_human() }})
                                </a>
                            </div>
                        </div>


                    </div>
                </div>
            {% endfor %}
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('community.scripts') }}"></script>
{% endblock %}