app/modules/password/models.py
from app import db


class Password(db.Model):
    id = db.Column(db.Integer, primary_key=True)

    def __repr__(self):
        return f"Password<{self.id}>"

app/modules/password/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField


class PasswordForm(FlaskForm):
    submit = SubmitField("Save password")

app/modules/password/__init__.py
from core.blueprints.base_blueprint import BaseBlueprint

password_bp = BaseBlueprint("password", __name__, template_folder="templates")

app/modules/password/routes.py
from flask import flash, redirect, render_template, request, url_for
from app.modules.password import password_bp
from app.modules.password.services import PasswordService
from itsdangerous import BadTimeSignature, SignatureExpired

password_service = PasswordService()


@password_bp.route("/password", methods=["GET"])
def index():
    return render_template("password/index.html")


@password_bp.route("/forgot/password", methods=["GET", "POST"])
def forgot_password():
    if request.method == "POST":
        try:
            email = request.form.get("email")
            if not email:
                flash("Please enter a valid email address", "danger")
                return redirect(url_for("password.forgot_password"))

            password_service.send_change_password_email(email)
            flash(
                "Check your email for the instructions to change your password",
                "success",
            )
            return redirect(url_for("auth.login"))

        except Exception as exc:
            flash(
                f"An error occurred while trying to change the password: {exc}",
                "danger",
            )
        return redirect(url_for("auth.login"))
    return render_template("password/forgot_password.html")


@password_bp.route("/change/password/<token>", methods=["GET", "POST"])
def change_password(token):
    try:
        email = password_service.get_email_by_token(token)
    except SignatureExpired:
        flash("Invalid or expired reset link.", "danger")
        return redirect(url_for("auth.login"))
    except BadTimeSignature:
        flash("The reset link has expired.", "danger")
        return redirect(url_for("auth.login"))

    if request.method == "POST":
        password = request.form["password"]
        confirm_password = request.form["confirm_password"]
        # Validación: Las contraseñas deben coincidir
        if password != confirm_password:
            flash("Passwords do not match. Please try again.", "danger")
            return render_template("password/change_password.html")
        password_service.change_password(email=email, password=password)
        flash("Your password has been updated!", "success")
        return redirect(url_for("auth.login"))
    return render_template("password/change_password.html")

app/modules/password/templates/password/change_password.html
{% extends "base_template.html" %}
{% block title %}Change password{% endblock %}
{% block content %}
<h1 class="h2 mb-3"><b>Change</b> password </h1>
<div class="row">
    <div class="col-md-4">
        <form action="{{ url_for('password.change_password', token=request.view_args['token']) }}" method="POST" id="change_password_form">
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label class="form-label" for="password">New password</label>
                        <input type="password" class="form-control" id="password" name="password" required>
                    </div>
                </div>
                <div class="col-12 mt-3">
                    <div class="form-group">
                        <label class="form-label" for="confirm_password">Confirm new password</label>
                        <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
                    </div>
                </div>
                <div class="col-12 mt-3">
                    <button type="submit" class="btn btn-primary" id="submit_button" disabled>Update Password</button>
                </div>
            </div>
            
        </form>
        
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="mt-3">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
</div>
{% endblock %}
{% block scripts %}
    <script src="{{ url_for('password.scripts') }}"></script>
{% endblock %}

app/modules/password/templates/password/forgot_password.html
{% extends "base_template.html" %}
{% block title %}Forgot password{% endblock %}
{% block content %}
<h1 class="h2 mb-3"><b>Forgot</b> password </h1>
<div class="row">
    <div class="col-md-6">
        <form action="{{ url_for('password.forgot_password') }}" method="post">
            <div class="row">
                <div class="col-12">
                    <div class="form-group">
                        <label class="form-label" for="email">Email</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                </div>
                <div class="col-12 mt-3">
                    <button type="submit" class="btn btn-primary">Change Password</button>
                </div>
            </div>
            
        </form>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div class="mt-3">
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
    </div>
</div>
{% endblock %}
{% block scripts %}
    <script src="{{ url_for('password.scripts') }}"></script>
{% endblock %}

app/modules/password/templates/password/index.html
{% extends "base_template.html" %}

{% block title %}View password{% endblock %}

{% block content %}

{% endblock %}

{% block scripts %}
    <script src="{{ url_for('password.scripts') }}"></script>
{% endblock %}